config/routes.rb
Rails.application.routes.draw do

	# ----- add these lines here: -----
    
	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	#root to: 'users#new'
	root to: 'home#index'
    get 'users/admin'	
    get 'users/welcome'
	get 'orders/index'
	get 'orders/adminhistory'
	post 'orders/adminhistory'
	get 'orders/report'
 
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
#	get 'sessions/new' => 'sessions#new', as: :new_session
	
	# create (post) action for when sign up form is submitted:
	post 'users' => 'users#create'

    get '/login'     => 'sessions#new', as: :new_session
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	get '/logout' => 'sessions#destroy', as: :destroy_session

  	# ----- end of added lines -----

	  get 'orders/new' => 'orders#new', as: :new_order

	  post 'orders' => 'orders#create'

    put 'orders' => 'orders#update'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
	validates :email, presence: true, uniqueness: true
    validates :password, confirmation: true
    validates :password_confirmation, presence: true

    has_many :orders
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    # ----- add these lines here: -----
  
    # Make the current_user method available to views also, not just controllers:
    helper_method :current_user
    
    # Define the current_user method:
    def current_user
      # Look up the current user based on user_id in the session cookie:
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    # ----- end of added lines -----
  
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    def about
    end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #before_action :set_order
  #before_action :authenticate_user!, except: [:index]
  #before_action :correct_user, only: [:new, :create]
    # ----- add these lines here: -----
    def index
        @orders = Order.all
    end
    def adminhistory
      @orders = Order.all
      
    end
    def report
      @orders = Order.all
      @users = User.all
      
    end
    def new
       # @order = Order.new
        @order = current_user.orders.build
    end
    def create
     #   @order = Order.new(order_params)
        @order = current_user.orders.build(order_params)
        num=0
        loop do
          number = SecureRandom.random_number(10000000)
          num = "GF#{number}"
          break num unless Order.where(orderId: num).exists?
        end


        @order.delivery_status="OUT FOR DELIVERY"
        @order.orderId=num
        if @order.save
          flash[:notice] = "Order placed successfully!"
        #  format.json { render :show, status: :created, location: @order }
          puts @order.orderId
          redirect_to users_welcome_path
        else
          # If user fails model validation - probably a bad password or duplicate email:
          flash.now.alert = "Oops, couldn't placed your order , please try again !."
          render :new
        end
    end
    def correct_user
      @order = current_user.orders.find_by(id: params[:id])
      redirect_to users_welcome_path, notice: "Not Authorized " if @order.nil?
    end
    private
    # def set_order
    #   @order = Order.find(id: params[:user_id])
    # end
    def order_params
        # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
        # that can be submitted by a form to the user model #=> require(:user)
        params.require(:order).permit(:orderId, :firstName, :lastName, :giftValue, :mobileNo, :address, :user_id, :delivery_status)
    end

      
    # ----- end of added lines -----
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
      def new
      end
    
      def create
        user = User.find_by(username: params[:login][:username].downcase)
         
        if user && user.authenticate(params[:login][:password]) && user.role==0
          session[:user_id] = user.id.to_s
          redirect_to users_welcome_path, notice: 'Successfully logged in! as User'
        elsif user && user.authenticate(params[:login][:password]) && user.role==1
          session[:user_id] = user.id.to_s
          redirect_to users_admin_path, notice: 'Successfully logged in! as Admin'
        else
          flash.now.alert = "Incorrect email or password, try again."
          render :new
        end
      end
    
      def destroy
        session.delete(:user_id)
        redirect_to login_path, notice: "Logged out!"
      end
      
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    def report
      @users = User.all
    end

    def create
        @user = User.new(user_params)
        @user.role=0
        @user.email.downcase!
    
        if @user.save
          flash[:notice] = "Account created successfully!"
          redirect_to root_path
        else
          flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
          render :new
        end
    end

   private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation,:role)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Gift Card</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
       <% if current_user%>
        <% if current_user.role == 0%>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>

          <div class="nav-link"><%= "Logged in as #{current_user.username}" %></div>
        </li>
        
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Home', users_welcome_path  %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'New Order', new_order_path  %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Order History', orders_index_path  %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link bg-danger"><%= link_to 'Log Out', destroy_session_path, method: :delete %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <% else %>
         <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>

          <div class="nav-link"><%= "Logged in as #{current_user.username}" %></div>
        </li>
        
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Home', users_welcome_path  %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Monthly Report', orders_report_path  %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Order History', orders_adminhistory_path  %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link bg-danger"><%= link_to 'Log Out', destroy_session_path, method: :delete %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <% end %>
       <% else %>

        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Home', root_path %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Log In', new_session_path %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
        <li class="nav-item">
          <div class="nav-link"><%= link_to 'Sign Up', new_user_path %></div>
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
       <% end %>
    <hr>
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="App">
      <header class="App-header">
        <h1 class='App-h1'>Welcome to Gift Card Application</h1>
        <%= link_to "Sign Up", new_user_path%>
        <br/><br/>
        <br/>
        <%= link_to "Sign In", new_session_path%>
      </header>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gift Card App</title>
    <%# <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
   <%= render 'home/header'%>
   

    <% if notice %>
      	    <%= notice %>
	  <% end %>
	
	  <% if alert %>
      	    <%= alert %>
	  <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/adminhistory.html.erb
<html>

<script>
function changeStatus()
{
  
}
</script>
<body>

<p style="color: green" ><%= notice %></p>

<h1>Orders History</h1>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Order Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Ordered Date</th>
        <th>Gift Card Value</th>
        <%# <th>Mobile No</th>
        <th>Address</th> %>
        <th>Commission<br>(10%)</th>
        <th>Delivery Status</th>
        <th>Action</th>
        <th colspan="3"></th>
      </tr>
    </thead>
 <tbody>
  
  <% @orders.each do |order| %>
      <tr>
          <td>
            <%= order.orderId%>
          </td>
          <td>
            <%= order.firstName%>
          </td>
          <td><%= order.lastName %></td>
          <td><%= order.created_at%></td>
          <td><%= order.giftValue %></td>
          <td><%= order.giftValue*0.1%></td>
          <% @x = order.orderId%>
          
          <td><strong><%= order.delivery_status%></strong></td>
          <% if order.delivery_status == "OUT FOR DELIVERY"%>
              <%# <td><%= button_to 'Mark Delivered',onclick="changeStatus()",class:"btn btn-primary" %>
              <td><button class="btn btn-primary" onclick="changeStatus()">Mark Delivered</button></td>
          <% elsif order.delivery_status == "OUT FOR DELIVERY"%>
              <td><%= button_to 'Mark DELIVERED', order.delivery_status = "DELIVERED" ,class:"btn btn-primary"  %></td>
          <% else %>
              <td><%= button_to 'Delivered' ,class:"btn btn-primary" %></td>
          <% end %>

          <%# <td><%= order.mobileNo %>
          <%# <td><%= order.address %>
        </tr> 
    <% end %>
 </tbody>
 
</table>

</body>
</html>

app/views/orders/index.html.erb
<p style="color: green" ><%= notice %></p>

<h1>Orders History</h1>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Order Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Ordered Date</th>
        <th>Gift Card Value</th>
        <%# <th>Mobile No</th>
        <th>Address</th> %>
        <th>Commission<br>(10%)</th>
        <th>Delivery Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
 <tbody>
  <% @orders.each do |order| %>
    <% if order.user == current_user %>
      <tr>
          <td>
            <%= order.orderId%>
          </td>
          <td>
            <%= order.firstName%>
          </td>
          
          
          <td><%= order.lastName %></td>
          <td><%= order.created_at%></td>
          <td><%= order.giftValue %></td>
          <td><%= order.giftValue*0.1%></td>
         <td><strong><%= order.delivery_status%></strong></td>

          <%# <td><%= order.mobileNo %>
          <%# <td><%= order.address %>
        </tr>
      <% end %>
    <% end %>
 </tbody>
</table>

app/views/orders/new.html.erb
<html>

<script>
function calComission()
{
  var v = parseInt(document.getElementById("val").value)
  console.log(v);
  var commission = parseInt(0.1*v);
  document.getElementById("total_amount").value = v + commission;
}
</script>
<body>



<div class="margin">
<div class="d-flex justify-content-around ">
<div class="card " >
  <div class="card-header text-center">
    <h2>New Order</h2>
  </div>
  <div class="card-body" style="width: 28rem ">
<%= form_for @order do |f| %>
  <div class="field form-group" class="col-xs-2">
    <strong><%= f.label :firstname %></strong>
    <%= f.text_field :firstName, autofocus: true ,class:"form-control"%>
  </div>
  <div class="field form-group">
    <strong><%= f.label :lastname %></strong>
    <%= f.text_field :lastName ,class:"form-control"%>
  </div>

  <div class="field form-group">
    
    <strong><%= f.label :GiftCardValue %></strong>
    <%= f.text_field :giftValue,class:"form-control" ,id:"val",onchange:"calComission()"%>
  </div>
  <div class="field form-group">
    <strong><%= f.label :AmountPayable %></strong>
    <%= f.text_field :giftValue,class:"form-control", id:"total_amount",value:"" %>
  </div>
  <div class="field form-group">
    <strong><%= f.label :mobileNumber %></strong>
    <%= f.text_field :mobileNo,class:"form-control" %>
  </div>
  <div class="field form-group">
    <strong><%= f.label :address %></strong>
    <%= f.text_field :address,class:"form-control" %>
  </div>
  <div class="field form-group">
    <%# <strong><%= f.label :UserId %></strong>
    <%= f.text_field :user_id, id: :order_user_id, value:current_user.id,type: :hidden,class:"form-control" %>
  </div>
  
  <div class="actions text-center">
    <%= f.submit "Place Order" ,class: "btn btn-primary"%>
  </div>
<% end %>
</div>
</div>

</div>
</div>

</body>
</html>

app/views/orders/report.html.erb
<p style="color: green" ><%= notice %></p>

<h1>Monthly Report</h1>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Order Id</th>
        <th>User Name</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Ordered Date</th>
        <th>Gift Card Value</th>
        <%# <th>Mobile No</th>
        <th>Address</th> %>
        <th>Commission<br>(10%)</th>
        <th>Delivery Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
 <tbody>
 <%@totalCommision = 0 %>
  <% @orders.each do |order| %>
      <tr>
          <td>
            <%= order.orderId%>
          </td>
          <% @x = @users.find_by(:id => order.user_id) %> 
          <td><%=  @x.username%>
          <td>
            <%= order.firstName%>
          </td>
          
        
          <td><%= order.lastName %></td>
          <td><%= order.created_at%></td>
          <td><%= order.giftValue %></td>
          <td><%= order.giftValue*0.1%></td>
         <% @totalCommision += order.giftValue*0.1%>
         <td><strong><%= order.delivery_status%></strong></td>

          <%# <td><%= order.mobileNo %>
          <%# <td><%= order.address %>
        </tr>
    <% end %>
 </tbody>

</table>

<h1>Total Commission :  <%= @totalCommision%> </h1>

app/views/users/admin.html.erb
<h1>Welcome to the Admin Page of Gift Card</h1>

app/views/users/new.html.erb
<div class="margin">
<div class="d-flex justify-content-around ">
<div class="card " >
  <div class="card-header text-center">
    <h2>Sign Up</h2>
  </div>
  <div class="card-body" style="width: 28rem ">
<%= form_for @user do |f| %>
  <div class="field form-group" class="col-xs-2">
    <strong><%= f.label :username %></strong>
    <%= f.text_field :username, autofocus: true ,class:"form-control"%>
  </div>
  <div class="field form-group">
    <strong><%= f.label :email %></strong>
    <%= f.text_field :email ,class:"form-control"%>
  </div>

  <div class="field form-group">
    
    <strong><%= f.label :password %></strong>
    <%= f.password_field :password,class:"form-control" %>
  </div>
  <div class="field form-group">
    <strong><%= f.label :password_confirmation %></strong>
    <%= f.password_field :password_confirmation,class:"form-control" %>
  </div>
  <div class="actions text-center">
    <%= f.submit "Sign Up" ,class: "btn btn-primary"%>
  </div>
  <h5 class="text-center">Having an account already? <%= link_to "Sign In", new_session_path%></h5>
<% end %>
</div>
</div>

</div>
</div>

app/views/users/welcome.html.erb
<h1>Welcome To Gift Card Home Page</h1>